# 全局异常处理

## 1. 简介

通常我们再Controller层需要去捕获service层的异常，防止返回一些不友好的错误信息到客户端，但如果Controller层每个方法都用模块化的try-catch代码去捕获异常，会很难看也难维护。

异常处理最好是解耦的，并且都放在一个地方集中管理。

- @ExceptionHandler：统一处理某一类异常，从而能够减少代码重复率和复杂度
- @ControllerAdvice：异常集中处理，更好的使业务逻辑与异常处理剥离开
- @ResponseStatus：可以将某种异常映射为HTTP状态码

单使用@ExceptionHandler，只能在当前Controller中处理异常，与@ControllerAdvice组合使用，则可以实现全局异常处理，不用每个controller都配置。

## 2. 代码示例

1. GlobalExceptionHandler 

   核心类@RestControllerAdvice和@ExceptionHandler 实现全局的异常处理。

   处理的内容包括，全局Exception，自定义的Exception，还有参数校验Exception

   ```JAVA
   package com.zszdevelop.globalexceptiondemo.handler;
   
   import com.zszdevelop.globalexceptiondemo.domain.Result;
   import com.zszdevelop.globalexceptiondemo.enums.ResultEnum;
   import com.zszdevelop.globalexceptiondemo.exception.AppException;
   import com.zszdevelop.globalexceptiondemo.utils.ResultUtil;
   import org.slf4j.Logger;
   import org.slf4j.LoggerFactory;
   import org.springframework.core.Ordered;
   import org.springframework.core.annotation.Order;
   import org.springframework.validation.BindException;
   import org.springframework.validation.FieldError;
   import org.springframework.web.bind.MethodArgumentNotValidException;
   import org.springframework.web.bind.annotation.ExceptionHandler;
   import org.springframework.web.bind.annotation.RestControllerAdvice;
   import java.util.List;
   
   /**
    * @作者: zhangshengzhong
    * @文件名: MessageController
    * @版本号:1.0
    * @创建日期: 2020/7/9 9:57
    * @描述: 全局异常处理
    */
   @RestControllerAdvice
   @Order(value = Ordered.HIGHEST_PRECEDENCE)
   public class GlobalExceptionHandler {
   
       private Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);
   
       @ExceptionHandler(value = Exception.class)
   //    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
       public Result handleException(Exception e) {
           logger.error(">>>>>>>系统内部异常，异常信息：", e);
           e.printStackTrace();
           return  ResultUtil.error("系统内部异常"+e.getMessage());
       }
   
       @ExceptionHandler(value = AppException.class)
   //    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
       public Result handleParamsInvalidException(AppException e) {
           logger.error(">>>>>>>系统错误：{}", e.getMessage());
           e.printStackTrace();
           return ResultUtil.error(e.getCode(),e.getMessage());
       }
   
       /**
        * 统一处理请求参数校验(实体对象传参)
        *
        * @param e BindException
        * @return FebsResponse
        */
       @ExceptionHandler(BindException.class)
   //    @ResponseStatus(HttpStatus.BAD_REQUEST)
       public Result validExceptionHandler(BindException e) {
           StringBuilder message = new StringBuilder();
           List<FieldError> fieldErrors = e.getBindingResult().getFieldErrors();
           for (FieldError error : fieldErrors) {
               message.append(error.getField()).append(error.getDefaultMessage()).append(",");
           }
           message = new StringBuilder(message.substring(0, message.length() - 1));
   
           return ResultUtil.error(ResultEnum.BIND_PARAMS_ERROR.getCode(),message.toString());
   
       }
   
   
       /**
        * 统一处理请求参数校验(json)
        *
        * @param e ConstraintViolationException
        * @return FebsResponse
        */
       @ExceptionHandler(MethodArgumentNotValidException.class)
   //    @ResponseStatus(HttpStatus.BAD_REQUEST)
       public Result handlerMethodArgumentNotValidException(MethodArgumentNotValidException e) {
           String COMMA = ",";
           StringBuilder message = new StringBuilder();
           for (FieldError error : e.getBindingResult().getFieldErrors()) {
               message.append(error.getField()).append(error.getDefaultMessage()).append(COMMA);
           }
           message = new StringBuilder(message.substring(0, message.length() - 1));
           logger.error(message.toString());
   
           return  ResultUtil.error(ResultEnum.BIND_PARAMS_ERROR.getCode(),message.toString());
       }
   
   }
   
   
   ```

2. 自定义异常 AppException(非必要，只是配合完整示例)

   ```java
   package com.zszdevelop.globalexceptiondemo.exception;
   
   
   import com.zszdevelop.globalexceptiondemo.enums.ResultEnum;
   
   /**
    * 异常统一处理
    * @author zhangshengzhong
    * @date 2019/9/3
    */
   public class AppException extends RuntimeException{
   
       private Integer code;
   
       public AppException(Integer code, String message) {
           super(message);
           this.code = code;
       }
   
       public AppException(ResultEnum resultEnum) {
           super(resultEnum.getMessage());
           this.code = resultEnum.getCode();
       }
   
       public Integer getCode() {
           return code;
       }
   }
   
   ```

3. 错误码ResultEnum(非必要，只是配合完整示例)

   ```java
   package com.zszdevelop.globalexceptiondemo.enums;
   
   
   /**
    * @author zhangshengzhong
    * @DATE 2019/9/3
    */
   public enum ResultEnum {
       // 错误信息
       SUCCESS(2000, "成功"),
       UNKNOWN_ERROR(5001,"未知错误"),
       BIND_PARAMS_ERROR(5002,"绑定参数异常" );
   
   
       private Integer code;
       private String message;
   
       ResultEnum(Integer code, String message) {
           this.code = code;
           this.message = message;
       }
   
       public Integer getCode() {
           return code;
       }
   
       public String getMessage() {
           return message;
       }
   }
   
   ```

4. 返回对象类Result(非必要，只是配合完整示例)

   ```java
   package com.zszdevelop.globalexceptiondemo.domain;
   
   import lombok.Data;
   
   import java.io.Serializable;
   
   /**
    * Created by zhangshengzhong on 2019/5/30.
    */
   @Data
   public class Result <T> implements Serializable{
       private static final long serialVersionUID = -2568788548483766212L;
   
       public static final int SUCCESS_CODE = 2000;
       // 5000以上为错误码，5000为默认错误码
       public static final int FAIL_CODE = 5000;
   
   
       private Integer code;
   
       private String msg;
   
       private T data;
   }
   
   ```

5. 返回结果工具类(非必要，只是配合完整示例)

   ```java
   package com.zszdevelop.globalexceptiondemo.utils;
   
   import com.zszdevelop.globalexceptiondemo.domain.Result;
   
   /**
    * @author 作者: zhangshengzhong
    * @文件名: ResultUtil
    * @版本号:1.0
    * @创建日期: 2020/12/9 10:57
    * @描述:
    */
   public class ResultUtil {
       public static Result success(Object object) {
           Result resultVO = new Result();
           resultVO.setCode(Result.SUCCESS_CODE);
           resultVO.setMsg("成功");
           resultVO.setData(object);
           return resultVO;
       }
   
       public static Result error(int code, String message) {
           Result resultVO = new Result();
           resultVO.setCode(code);
           resultVO.setMsg(message);
           return resultVO;
       }
   
       public static Result error(String message) {
           return error(Result.FAIL_CODE,message);
       }
   
   
   }
   
   ```

   

## 参考文章

[Java 代码中的全局异常处理](https://testerhome.com/topics/12058)